import type { Metadata } from "next";
import "../globals.css";
import StoreProvider from "../StoreProvider";
import SessionProviderWrapper from "../SessionProviderWrapper";


export const metadata: Metadata = {
  title: "CodeCompass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProviderWrapper>
      <StoreProvider>
        <main>{children}</main>
      </StoreProvider>
    </SessionProviderWrapper>
  );
}

