import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import SessionProviderWrapper from "./SessionProviderWrapper";

const barlow = Barlow({
  weight: "400",
  weight: "400",
  variable: "--font-barlow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeCompass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={barlow.className}>
      <body className={`${barlow.variable} antialiased`}>
        <SessionProviderWrapper>
          <StoreProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </StoreProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}

