name: Build and Deploy Code Compass

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: next-code-compass

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create commit SHA tag
      - name: Set TAG
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Show TAG value
        run: echo "Using TAG ${{ env.TAG }}"

      # Login to Docker Hub
      - name: Login to Docker Registry
        run: echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

      # Build and tag image with SHA and latest
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg OIDC_CLIENT_ID=${{ secrets.OIDC_CLIENT_ID }} \
            --build-arg OIDC_CLIENT_SECRET=${{ secrets.OIDC_CLIENT_SECRET }} \
            --build-arg OIDC_ISSUER=${{ secrets.OIDC_ISSUER }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            --build-arg BASE_URL_CODE_COMPASS=${{ secrets.BASE_URL_CODE_COMPASS }} \
            --build-arg NEXT_PUBLIC_BASE_URL_CODE_COMPASS=${{ secrets.NEXT_PUBLIC_BASE_URL_CODE_COMPASS }} \
            --build-arg CCP_GITHUB_CLIENT_ID=${{ secrets.CCP_GITHUB_CLIENT_ID }} \
            --build-arg CCP_GITHUB_CLIENT_SECRET=${{ secrets.CCP_GITHUB_CLIENT_SECRET }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      # Push both tags
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Registry
        if: always()
        run: docker logout

      # Deploy to server via SSH
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.USERNAME }}
            cd front/
            docker compose down
            docker pull $DOCKER_USERNAME/next-code-compass:latest
            docker compose up -d --force-recreate --remove-orphansimplementing